// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateListing.Models;

namespace RealEstateListing.Migrations
{
    [DbContext(typeof(RealEstateListingContext))]
    partial class RealEstateListingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RealEstateListing.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location");

                    b.Property<DateTime?>("SoldDate");

                    b.Property<string>("SoldTo");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Cincinnati",
                            Type = "Open Land"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Columbus",
                            Type = "Apartment"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Cincinnati",
                            Type = "Farm House"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Dayton",
                            Type = "Building"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
